name: vampire
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - h5py=2.10.0
  - biopython
  - click
  - flake8
  - keras=2.2.5
  - matplotlib
  - pandas
  - parallel
  - pip
  - pydot
  - pytest
  - scikit-learn
  - scons
  - seaborn
  - yapf
  - pip:
    - delegator.py
    - exrex
    - nestly
    - versioneer
