import os

from os.path import join
from nestly.scons import SConsWrap
from nestly import Nest

Import('env')
localenv = env.Clone()

nest = SConsWrap(Nest(), alias_environment=localenv)

DATA = {
    'test': {
        'path': '02-0249_TCRB.head.tsv',
    }
}

nest.add(
    'data', [
        'test',
    ], label_func=lambda c: f'_output_{c}')


@nest.add_target_with_env(localenv)
def read_gestalt(env, outdir, c):
    in_path = DATA[c['data']]['path']
    return env.Command(
        join(
            outdir,
            os.path.splitext(os.path.basename(in_path))[0] + '.processed.csv'),
        in_path, 'python3 preprocess_adaptive.py $SOURCE $TARGET')
