#!/usr/bin/env scons
"""
The master SConstruct file; particular analyses run via SConscript files in
subdirectories.
"""

import os

from os.path import join

import SCons.Script as sc

# Command line options

sc.AddOption(
    '--pipe',
    type='string',
    help="Which pipeline to run.",
    default='pipe_main')

sc.AddOption(
    '--data',
    type='string',
    help="Which data to run in the specified pipeline.",
    default='test')

# Set up environment and run  \m/ ( -_- ) \m/

env = sc.Environment(ENV=os.environ, data=sc.GetOption('data'))
sc.Export('env')
sc.SConscript(join(sc.GetOption('pipe'), 'SConscript'))
