#!/usr/bin/env scons
"""
The master SConstruct file; particular analyses run via SConscript files in
subdirectories.
"""

import os

from os.path import join

import SCons.Script as sc

# Command line options
sc.AddOption('--pipe', type='string', help="Which pipeline to run.", default='pipe_main')
sc.AddOption('--data', type='string', help="The label of the data to be run in the specified pipeline.", default='dryrun')
sc.AddOption('--test', type='string', help="The label of the data to be used as test.", default='dryrun')
sc.AddOption(
    '--mode', type='string', help="The mode of the run, which is up to the SConscript to define.", default='default')
sc.AddOption('--clusters', type='string', help="Clusters to submit to. Default is local execution.", default='')
sc.AddOption('--test-size', type=float, help="Proportion of sample to hold out for testing.", default=0.5)

# Set up environment and run  \m/ ( -_- ) \m/
env = sc.Environment(
    ENV=os.environ,
    data_label=sc.GetOption('data'),
    test_label=sc.GetOption('test'),
    mode=sc.GetOption('mode'),
    clusters=sc.GetOption('clusters'),
    test_size=sc.GetOption('test_size'))
sc.Export('env')
sc.SConscript(join(sc.GetOption('pipe'), 'SConscript'))
